name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-and-test:
    name: Lint and Test
    runs-on: windows-latest  # Mantido o Windows runner

    steps:
      # Step 1: Fazer checkout do código
      - name: Check out code
        uses: actions/checkout@v3

      # Step 2: Baixar e instalar PostgreSQL no Windows
      - name: Install PostgreSQL
        run: |
          choco install postgresql --version=17.0 -y
          setx PATH "$Env:Path;C:\Program Files\PostgreSQL\17\bin"


      # Step 3: Iniciar o serviço do PostgreSQL
      - name: Verify PostgreSQL Version
        run: psql --version

      # Step 4: Criar o banco de dados para testes
      - name: Create test database
        run: |
          psql -U postgres -c "CREATE DATABASE test_db;"

      # Step 5: Configurar o Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      # Step 6: Instalar dependências
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 pytest psycopg2-binary pandas faker

      # Step 7: Configurar variáveis de ambiente do banco
      - name: Set database environment variables
        run: |
          echo "DB_USER=postgres" >> $GITHUB_ENV
          echo "DB_PASSWORD=sql12345" >> $GITHUB_ENV
          echo "DB_NAME=test_db" >> $GITHUB_ENV
          echo "DB_HOST=localhost" >> $GITHUB_ENV
          echo "DB_PORT=5432" >> $GITHUB_ENV

      # Step 8: Rodar flake8
      - name: Run flake8
        run: flake8 --config=.flake8 .

      # Step 9: Rodar pytest
      - name: Run pytest
        env:
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
        run: pytest --no-header -vv
