name: CI Pipeline

on:
  push:
    branches:
      - main  # Executa o pipeline em cada push para a branch main
  pull_request:
    branches:
      - main  # Executa o pipeline em cada PR para a branch main

jobs:
  lint-and-test:
    name: Lint and Test
    runs-on: windows-latest  # Use windows-latest se estiver usando Windows

    steps:
      # Step 1: Fazer checkout do código
      - name: Check out code
        uses: actions/checkout@v3

      # Step 2: Configurar o Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"  # Escolha a versão do Python

      # Step 3: Instalar dependências
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 pytest  # Adicionar ferramentas diretamente
          pip install psycopg2-binary
          pip install pandas

      # Step 4: Rodar flake8
      - name: Run flake8
        run: flake8 --config=.flake8 .

      # Step 5: Rodar pytest
      - name: Run pytest
        run: pytest --no-header -vv


